runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: app.app

libraries:
- name: MySQLdb
  version: "latest"

# [START env_variables]
env_variables:
    CLOUDSQL_CONNECTION_NAME: master-deck-148904:us-central1:rmcinstance
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: rmcinstance
    CLOUDSQL_DB: Classes
# [END env_variables]
